name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    # Enable trace on first retry (so failed tests have trace)
    - name: Run Playwright tests
      run: npx playwright test --trace on-first-retry --reporter=html,json

    # Prepare report folder with run ID
    - name: Prepare report folder
      if: always()
      run: |
        mkdir -p public/reports
        RUN_ID=${GITHUB_RUN_ID}
        mv playwright-report public/reports/${RUN_ID}
        echo "${RUN_ID}" > public/latest_run.txt

    # Generate/Update index.html table
    - name: Update results table
      if: always()
      run: |
        RUN_ID=${GITHUB_RUN_ID}
        DATE=$(date +"%Y-%m-%d %H:%M:%S")
        PASSED=$(jq '[.suites[].tests[] | select(.status=="passed")] | length' playwright-report.json)
        FAILED=$(jq '[.suites[].tests[] | select(.status=="failed")] | length' playwright-report.json)
        ROW="<tr><td>${DATE}</td><td>${PASSED}</td><td>${FAILED}</td><td><a href='reports/${RUN_ID}/index.html'>View Report</a></td></tr>"

        if [ ! -f public/index.html ]; then
          echo "<html><body><h1>Playwright Test Results</h1><table border='1'><tr><th>Run date</th><th>Tests passed</th><th>Tests failed</th><th>Link</th></tr>${ROW}</table></body></html>" > public/index.html
        else
          sed -i "s|</table>|${ROW}</table>|" public/index.html
        fi

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
